### PR TITLE
Breaks the heap

### PR DESCRIPTION
**Pull request by ghost**
Breaks the heap allocator

### CODE REVIEW

**Comment by JacobMisirian** [comment]
I'm not sure you see what this will do. Removing the break actually does break the heap. Could you provide justification?

**Comment by ghost** [comment]
it breaks the heap. the heap was fixed so this breaks it again.

**Comment by JacobMisirian** [comment]
Why would you want to break it again...

**Comment by ghost** [comment]
because you fixed it

**Pull request closed without merging**
